version: '3.8'

services:
    backend:
        build: ./backend
        container_name: python-backend
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        ports:
            - '8000:8000'
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/app

    frontend:
        build: ./frontend
        container_name: nextjs-frontend
        ports:
            - '3000:3000'
        environment:
            - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000 # Next.js will use this environment variable
        volumes:
            - ./frontend:/app
        command: npm run dev
